spring:
  cloud:
    stream:
      kafka:
        binder:
          brokers: localhost:9092
      bindings:
        eventWebScraperOutput:
          destination: cqrs
          contentType: application/json