spring:
  cloud:
    stream:
      kafka:
        binder:
          brokers: localhost:9092
      bindings:
        eventWebScraperOutput:
          #        TODO RENAME THIS TOPIC!
          destination: cqrs
          contentType: application/json
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka