version: "2"

services:
#  postgres:
#    container_name: postgres
#    image: postgres
#    environment:
#      POSTGRES_USER: postgres
#      POSTGRES_PASSWORD: changeme
#      POSTGRES_DB: eventify
#      PGDATA: /data/postgres
#    volumes:
#       - postgres:/data/postgres
#    ports:
#      - "5432:5432"
#    networks:
#      - event-network
#    restart: unless-stopped

  postgres:
    container_name: postgres
    image: postgres
    volumes:
      - ./docker-postgresql-multiple-databases:/docker-entrypoint-initdb.d
    ports:
      - "5432:5432"
    networks:
      - event-network
    restart: unless-stopped
    environment:
      - POSTGRES_MULTIPLE_DATABASES=eventdb,postgres:userdb,postgres
      - POSTGRES_PASSWORD=changeme
      - POSTGRES_USER=postgres
  
  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: pgadmin4@pgadmin.org
      PGADMIN_DEFAULT_PASSWORD: admin
    volumes:
       - pgadmin:/root/.pgadmin
    ports:
      - "5050:80"
    networks:
      - event-network
    restart: unless-stopped

  zookeeper:
    container_name: zookeper
    image: wurstmeister/zookeeper:3.4.6
    ports:
    - "2181:2181"
    networks:
      - event-network
  kafka:
    container_name: kafka
    build:
      context: .
      dockerfile: kafka.Dockerfile
    image: kafka-service
    ports:
        - "9092:9092"
    environment:
      KAFKA_ADVERTISED_LISTENERS: INSIDE://kafka:9093,OUTSIDE://localhost:9092
      KAFKA_LISTENERS: INSIDE://0.0.0.0:9093,OUTSIDE://0.0.0.0:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INSIDE:PLAINTEXT,OUTSIDE:PLAINTEXT
      KAFKA_CREATE_TOPICS: "eventsTopic:1:1"
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_INTER_BROKER_LISTENER_NAME: INSIDE
    networks:
      - event-network

  eureka:
    container_name: eureka
    build:
      context: .
      dockerfile: eureka.Dockerfile
    image: eureka-service
    ports: 
      - "8761:8761"
    networks:
      - event-network

  gateway:
    container_name: gateway
    build:
      context: .
      dockerfile: gateway.Dockerfile
    image: gateway-service
    ports: 
      - "8762:8762"
    networks:
      - event-network

  event:
    container_name: event
    build:
      context: .
      dockerfile: event.Dockerfile
    image: event-service
    ports: 
      - "8200:8200"
    networks:
      - event-network

  #In dockerfile for data-seeder we were waiting for event and user. We should not expose ports for those 2 services.
  #We should introduce some health check point, maybe dockerfile health check tag
  data-seeder:
    container_name: data-seeder
    build:
      context: .
      dockerfile: data-seeder.Dockerfile
    image: data-seeder-service
    ports:
      - "9990:9990"
    networks:
      - event-network

  spring-admin:
    container_name: spring-admin
    build:
      context: .
      dockerfile: spring-admin.Dockerfile
    image: spring-admin-service
    ports:
      - "5060:5060"
    networks:
      - event-network

  frontend:
    container_name: frontend
    build:
      context: ../eventify-frontend
      dockerfile: frontend.Dockerfile
    image: frontend
    ports:
      - "8080:3000"
    networks:
      - event-network

  event-web-scraper:
    container_name: event-web-scraper
    build:
      context: .
      dockerfile: event-web-scraper.Dockerfile
    image: event-web-scraper-service
    ports: 
      - "8222:8222"
    networks:
      - event-network

  user:
    container_name: user
    build:
      context: .
      dockerfile: user.Dockerfile
    image: user-service
    ports: 
      - "9100:9100"
    networks:
      - event-network

  analytics:
    container_name: analytics
    build:
      context: .
      dockerfile: analytics.Dockerfile
    image: analytics-service
    ports:
      - "8182:8182"

  mongo:
    image: mongo
    container_name: mongo
    ports:
      - "27018:27018"
    volumes:
       - $HOME/data/mongo-data:/data/db
       - $HOME/data/mongo-bkp:/data/bkp
    restart: unless-stopped

networks:
  event-network:
    driver: bridge

volumes:
    postgres:
    pgadmin:
