/**
 * Created by spasoje on 09-Dec-18.
 */

const actions = {
    GET_EVENTS:'GET_EVENTS',
    GET_EVENTS_SUCCESS:'GET_EVENTS_SUCCESS',
    GET_EVENTS_FAIL:'GET_EVENTS_FAIL',
    GET_EVENTS_BY_FILTER:'GET_EVENTS_BY_FILTER',
    GET_EVENTS_BY_FILTER_SUCCESS:'GET_EVENTS_BY_FILTER_SUCCESS',
    GET_EVENTS_BY_FILTER_FAIL:'GET_EVENTS_BY_FILTER_FAIL',
    FILTER_CHANGED:'FILTER_CHANGED',
    ADD_EVENT:'ADD_EVENT',
    ADD_EVENT_SUCCESS:'ADD_EVENT_SUCCESS',
    ADD_EVENT_FAIL:'ADD_EVENT_FAIL'
}

export default actions;