spring:
  cloud:
    stream:
      kafka:
        binder:
          brokers: localhost:9092
      bindings:
        eventInput:
#        TODO RENAME THIS TOPIC!
          destination: cqrs
          contentType: application/json
        eventOutput:
#        TODO RENAME THIS TOPIC
          destination: cqrs1
          contentType: application/json