spring:
  cloud:
    stream:
      kafka:
        binder:
          brokers: localhost:9092
      bindings:
        eventsTopicInputChannel:
          destination: eventsTopic
          contentType: application/json
        eventsTopicOutputChannel:
          destination: eventsTopic
          contentType: application/json
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka