spring:
  cloud:
    stream:
      kafka:
        binder:
          brokers: kafka:9093
      bindings:
        eventsTopic:
          destination: eventsTopic
          contentType: application/json
eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka:8761/eureka