/**
 * Created by spasoje on 09-Dec-18.
 */

const actions = {
    GET_EVENTS_BY_FILTER:'GET_EVENTS_BY_FILTER',
    GET_EVENTS_BY_FILTER_SUCCESS:'GET_EVENTS_BY_FILTER_SUCCESS',
    GET_EVENTS_BY_FILTER_FAIL:'GET_EVENTS_BY_FILTER_FAIL',
    UPDATE_EVENT:'UPDATE_EVENT',
    UPDATE_EVENT_SUCCESS:'UPDATE_EVENT_SUCCESS',
    UPDATE_EVENT_FAIL:'UPDATE_EVENT_FAIL',
    GET_EVENT_BY_ID:'GET_EVENT_BY_ID',
    GET_EVENT_BY_ID_SUCCESS:'GET_EVENT_BY_ID_SUCCESS',
    GET_EVENT_BY_ID_FAIL:'GET_EVENT_BY_ID_FAIL',
    CHANGE_FILTER_SUCCESS:'CHANGE_FILTER_SUCCESS',
    ADD_EVENT:'ADD_EVENT',
    ADD_EVENT_SUCCESS:'ADD_EVENT_SUCCESS',
    ADD_EVENT_FAIL:'ADD_EVENT_FAIL'
}

export default actions;