spring:
  cloud:
    stream:
      kafka:
        binder:
          brokers: kafka:9092
      bindings:
        authInput:
#        TODO RENAME THIS TOPIC!
          destination: cqrs1
          contentType: application/json
